### ISSUE TITLE
Problem plotting netVisual_bubble

### ISSUE THREAD

**Issue by ccruizm** [sqjin/CellChat#107]
Good day!

Great package! The new tutorials are awesome. I am following them with my own data but have problems when trying to plot `netVisual_bubble`. I can see the different pathways using `netVisual_aggregate` but can't see them in the bubble plot. Below the error:
```
Comparing communications on a single object 


Error in `$<-.data.frame`(`*tmp*`, "interaction_name_2", value = "MIF - (CD74+CXCR4)"): replacement has 1 row, data has 0
Traceback:

1. netVisual_bubble(cellchat, sources.use = 2, targets.use = c(3:5), 
 .     remove.isolate = FALSE)
2. `$<-`(`*tmp*`, "interaction_name_2", value = "MIF - (CD74+CXCR4)")
3. `$<-.data.frame`(`*tmp*`, "interaction_name_2", value = "MIF - (CD74+CXCR4)")
4. stop(sprintf(ngettext(N, "replacement has %d row, data has %d", 
 .     "replacement has %d rows, data has %d"), N, nrows), domain = NA)
```
What do you think might be the problem?

My sessionInfo:
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /hpc/pmc_stunnenberg/cruiz/miniconda3/envs/r_env_4.0.3/lib/libopenblasp-r0.3.10.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] gdtools_0.2.2       future_1.21.0       Seurat_3.9.9.9024  
 [4] dplyr_1.0.2         igraph_1.2.6        ggalluvial_0.12.3  
 [7] patchwork_1.1.1     ggplot2_3.3.3.9000  CellChat_0.5.0     
[10] Biobase_2.50.0      BiocGenerics_0.36.0

loaded via a namespace (and not attached):
  [1] uuid_0.1-4             circlize_0.4.12.1006   systemfonts_0.3.2     
  [4] NMF_0.23.0             plyr_1.8.6             repr_1.1.0            
  [7] lazyeval_0.2.2         splines_4.0.3          listenv_0.8.0         
 [10] scattermore_0.7        gridBase_0.4-7         digest_0.6.27         
 [13] foreach_1.5.1          htmltools_0.5.0        magrittr_2.0.1        
 [16] rle_0.9.2              tensor_1.5             cluster_2.1.0         
 [19] doParallel_1.0.16      ROCR_1.0-11            sna_2.6               
 [22] ComplexHeatmap_2.7.4   globals_0.14.0         matrixStats_0.57.0    
 [25] gg.gap_1.4             svglite_1.2.3.2        colorspace_2.0-0      
 [28] ggrepel_0.9.0          crayon_1.3.4           jsonlite_1.7.2        
 [31] spatstat_1.64-1        spatstat.data_1.7-0    survival_3.2-7        
 [34] zoo_1.8-8              iterators_1.0.13       glue_1.4.2            
 [37] polyclip_1.10-0        registry_0.5-1         gtable_0.3.0          
 [40] leiden_0.3.6           GetoptLong_1.0.5       future.apply_1.7.0    
 [43] shape_1.4.5            abind_1.4-5            scales_1.1.1          
 [46] rngtools_1.5           miniUI_0.1.1.1         Rcpp_1.0.5            
 [49] viridisLite_0.3.0      xtable_1.8-4           clue_0.3-58           
 [52] reticulate_1.18        rsvd_1.0.3             stats4_4.0.3          
 [55] htmlwidgets_1.5.3      httr_1.4.2             FNN_1.1.3             
 [58] RColorBrewer_1.1-2     ellipsis_0.3.1         ica_1.0-2             
 [61] farver_2.0.3           pkgconfig_2.0.3        uwot_0.1.10           
 [64] deldir_0.2-3           labeling_0.4.2         tidyselect_1.1.0      
 [67] rlang_0.4.10           reshape2_1.4.4         later_1.1.0.1         
 [70] munsell_0.5.0          tools_4.0.3            generics_0.1.0        
 [73] statnet.common_4.4.1   ggridges_0.5.2         evaluate_0.14         
 [76] stringr_1.4.0          fastmap_1.0.1          goftest_1.2-2         
 [79] fitdistrplus_1.1-3     purrr_0.3.4            RANN_2.6.1            
 [82] nlme_3.1-150           pbapply_1.4-3          mime_0.9              
 [85] compiler_4.0.3         plotly_4.9.2.2         png_0.1-7             
 [88] spatstat.utils_1.17-0  tibble_3.0.4           stringi_1.5.3         
 [91] RSpectra_0.16-0        forcats_0.5.0          lattice_0.20-41       
 [94] IRdisplay_0.7.0        Matrix_1.2-18          vctrs_0.3.6           
 [97] pillar_1.4.7           lifecycle_0.2.0        lmtest_0.9-38         
[100] GlobalOptions_0.1.2    RcppAnnoy_0.0.18       data.table_1.13.6     
[103] cowplot_1.1.1          irlba_2.3.3            httpuv_1.5.4          
[106] R6_2.5.0               promises_1.1.1         network_1.16.1        
[109] KernSmooth_2.23-18     gridExtra_2.3          IRanges_2.24.1        
[112] parallelly_1.23.0      codetools_0.2-18       MASS_7.3-53           
[115] assertthat_0.2.1       pkgmaker_0.32.2        rjson_0.2.20          
[118] withr_2.3.0            sctransform_0.3.2.9001 S4Vectors_0.28.1      
[121] mgcv_1.8-33            rpart_4.1-15           grid_4.0.3            
[124] IRkernel_1.1.1         tidyr_1.1.2            coda_0.19-4           
[127] Cairo_1.5-12.2         Rtsne_0.15             pbdZMQ_0.3-3.1        
[130] shiny_1.5.0            base64enc_0.1-3 
```
Thanks in advance!

**Comment by sqjin** [comment]
Hi @ccruizm , I think I have replicated your error, and the bug should be fixed now. Please reinstall and check it.

**Comment by ccruizm** [comment]
Thanks for your reply @sqjin! However, I just installed the new version and still get the same error. I used another dataset but the same output. This is the only part of the workflow that does not work. All other steps and plots run smoothly.

**Comment by lyuguol** [comment]
> Hi @ccruizm , I think I have replicated your error, and the bug should be fixed now. Please reinstall and check it.

Yes. I also had the similar problem when running 

netVisual_bubble(cellchat, sources.use = c(3, 8), targets.use = 10, remove.isolate = FALSE)

I re-installed CellChat a few minutes ago, re-ran and still got the same error.

Maybe restart R could help??

In addition, do we need to run 'cellchat <- rankNetPairwise(cellchat)' beforenet ruuning 'Visual_bubble(cellchat)' with the new release version of CellChat?

Thank you very much!!

Guoliang

**Comment by sqjin** [comment]
@ccruizm @lyuguol It should be fixed now! ! I forgot to fix it in the analysis of individual object.

**Comment by lyuguol** [comment]
> @ccruizm @lyuguol It should be fixed now! ! I forgot to fix it in the analysis of individual object.

@sqjin Many thanks for the quick reply!!

I re-installed CellChat and re-ran after receiving your reply.

However, everything went well before I got the following errors:

netVisual_bubble(cellchat, sources.use = 1, targets.use = 2, remove.isolate = FALSE)
Comparing communications on a single object 

Error in `$<-.data.frame`(`*tmp*`, "interaction_name_2", value = "Tgfb1 - (Tgfbr1+Tgfbr2)") : 
  replacement has 1 row, data has 0

netVisual_bubble(cellchat, sources.use = 4, targets.use = c(5:11), signaling = c("CCL","CXCL"), remove.isolate = FALSE)
Comparing communications on a single object 

Error in seq.default(1.5, length(unique(df$interaction_name_2)) - 0.5,  : 
  wrong sign in 'by' argument

Do you know how to explain and fix it?

Thanks a lot!

Have a nice weekend,

Guoliang

**Comment by sqjin** [comment]
Hi @lyuguol , are you running the example data in the tutorial? I have no issue to run this tutorial.  I have also played with several cases for generating the bubble plot, but I did not find any bug.  If you can share the data, I am happy to test it; otherwise, please run the source codes to figure out the bug and let me know.

**Comment by lyuguol** [comment]
> Hi @lyuguol , are you running the example data in the tutorial? I have no issue to run this tutorial. I have also played with several cases for generating the bubble plot, but I did not find any bug. If you can share the CellChat object, I am happy to test it; otherwise, please run the source codes to figure out the bug and let me know.

Hello @sqjin , I re-ran again. I do not know what happened, no error is there anymore...

I would say 'CellChat' is really the most amazing tool for single cell-cell communication analysis at the moment!!!

Many thanks to you and your team!!

Best,

Guoliang

**Comment by ccruizm** [comment]
Thanks for fixing it! quick question: is there a way to set the order of the columns/rows of the plots? (for instance, using `netVisual_heatmap`)

**Comment by ccruizm** [comment]
Btw, after the last update, when using `rankNet` the color of the labels is inverted (does not match the bars). See below.

<img width="588" alt="Screenshot 2021-01-12 at 17 08 22" src="https://user-images.githubusercontent.com/37718031/104340257-c9407780-54f8-11eb-8f3e-36b1ab8d6d36.png">

**Comment by sqjin** [comment]
@ccruizm Fixed the color issue! I can consider adding an option in `netVisual_heatmap` later.

**Comment by ccruizm** [comment]
Works perfectly! thanks @sqjin!
