### ISSUE TITLE
Error when running netVisual_Aggregate

### ISSUE THREAD

**Issue by laujm** [sqjin/CellChat#569]
Hi,

I was trying to remake some circle plots using netVisual_Aggregate and have continued getting this error. 
I have run the code previously with the same pathways and did not run into this error. The objects that I used were the same, but with some communication removed as I wanted to look at signaling between specific populations. To see if the error was object related, I ran the code with the old object that previously did not output an error, but I ended up getting an error even with the older object. 

```
Error` in i_set_edge_attr(x, attr(value, "name"), index = value, value = attr(value,  : 
  Length of new attribute value must be 1 or 66, the number of target edges, not 58
```

Here is my code. The cellchat object is a merged object with four groups. 

```
pathways <- c("TGFb", "APP", "THY1", "VISFATIN", "TENASCIN", "SEMA3", "HGF", "BMP")
pathways.show <- pathways[1]
par(mfrow = c(2,2), xpd=TRUE)

weight.max <- getMaxWeight(object.list[1:4], slot.name = c("netP"), attribute = pathways.show)
for (i in 1:length(object.list)) {
  netVisual_aggregate(object.list[[i]], vertex.receiver = vertex.receiver, signaling = pathways.show, layout = "circle", vertex.weight = NULL, edge.weight.max = weight.max[1], signaling.name = paste(pathways.show, names(object.list)[i]), arrow.size = 0.3)
}

```

I have tried to look into the source code, but cannot figure out what the error means. 

Thank you!

**Comment by pjmoos** [comment]
hello I have also had a similar situation.  If I run:
`pathways.show <- c("BMP") 
weight.max <- getMaxWeight(object.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
par(mfrow = c(1,2), xpd=TRUE)
for (i in 1:length(object.list)) {
  netVisual_aggregate(object.list[[i]], signaling = pathways.show, layout = "circle", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(object.list)[i]))
}`
everything works as expected; however, if I change the pathway to "ncWNT" I get an error:
`Error in i_set_edge_attr(x, attr(value, "name"), index = value, value = attr(value, :
Length of new attribute value must be 1 or 36, the number of target edges, not 21`
I am unclear why it works for some pathways and not others - all pathways that I'm asking for graphics for have been identified as significant.
Thank you!

**Comment by laujm** [comment]
> hello I have also had a similar situation. If I run: `pathways.show <- c("BMP")
> 
> weight.max <- getMaxWeight(object.list, slot.name = c("netP"), attribute = pathways.show) # control the edge weights across different datasets
> 
> par(mfrow = c(1,2), xpd=TRUE)
> 
> for (i in 1:length(object.list)) {
> 
> netVisual_aggregate(object.list[[i]], signaling = pathways.show, layout = "circle", edge.weight.max = weight.max[1], edge.width.max = 10, signaling.name = paste(pathways.show, names(object.list)[i]))
> 
> }`
> 
> everything works as expected; however, if I change the pathway to "ncWNT" I get an error: `Error in i_set_edge_attr(x, attr(value, "name"), index = value, value = attr(value, : Length of new attribute value must be 1 or 36, the number of target edges, not 21` I am unclear why it works for some pathways and not others - all pathways that I'm asking for graphics for have been identified as significant. Thank you!

Hi,

I fixed this by updating the object using updateCellchat(). Hope this helps.

**Comment by pjmoos** [comment]
I am using CellChat_1.6.1, I also tried updateCellChat() and still have the same errors – works for some pathways but not others.
Thanks,
philip
